
services:
  postgres:
    image: postgres:latest
    container_name: company_export
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: company_export
    ports:
      - "54321:5432"
    volumes:
      - company_export:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  company_export:
